# Shopping Cart Constants
FONT_SIZE = 12
SHOPPING_CART_X_SIZE = 100
SHOPPING_CART_OFFSET_X = 50
SHOPPING_CART_OFFSET_Y = 70

# User Constants
MAX_USER_EMAIL_LENGTH = 254
MAX_USER_USERNAME_LENGTH = 150
MAX_USER_FIRSTNAME_LENGTH = 150
MAX_USER_LASTNAME_LENGTH = 150

# Any
PAGINATION_PAGE_SIZE = 6
