# Tags Constants
MAX_TAG_NAME_LENGTH = 32
MAX_TAG_SLUG_LENGTH = 32

# Ingredients Constants
MAX_INGREDIENT_NAME_LENGTH = 128
MAX_INGREDIENT_MEASURE_UNIT_LENGTH = 64

# Recipe Constants
MAX_RECIPE_NAME_LENGTH = 256
