# Generated by Django 3.2 on 2024-11-01 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20241029_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Минимальное значение - 1'), django.core.validators.MaxValueValidator(1000, 'Максимальное значение - 1000')], verbose_name='Время готовки'),
        ),
        migrations.AlterField(
            model_name='recipesingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Минимальное значение - 1'), django.core.validators.MaxValueValidator(10000, 'Максимальное значение - 10000')], verbose_name='Количество'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favorites'),
        ),
        migrations.AddConstraint(
            model_name='recipesingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipes'),
        ),
        migrations.AddConstraint(
            model_name='shopping_cart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_shop_cart'),
        ),
    ]
