# Generated by Django 3.2 on 2024-10-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Подписка'),
        ),
    ]
