# Generated by Django 3.2 on 2024-10-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20241004_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Подписка'),
        ),
    ]
