# Generated by Django 3.2 on 2024-10-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Подписка'),
        ),
    ]
