# Generated by Django 3.2 on 2024-10-28 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='user',
        ),
        migrations.AddField(
            model_name='subscribers',
            name='subscribe_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_to', to='users.user', verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribers',
            name='subscriber',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='users.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
