# Generated by Django 3.2 on 2024-10-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_is_subscribed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribers',
            constraint=models.UniqueConstraint(fields=('subscriber', 'subscribe_to'), name='unique_subscribers'),
        ),
    ]
