# Generated by Django 3.2 on 2024-11-01 10:13

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_subscribers_unique_subscribers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribers',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, subscriber=django.db.models.expressions.F('subscribe_to')), name='cannot_subscribe_to_self'),
        ),
    ]
